# Meta configuration for entire solver
logging_level: INFO
llm_mode: offline
repair_enabled: true
repair_threshold: 0.7
reflex_override:
  enabled: true
  threshold: 0.45
  default_path: fallback
prior_injection:
  enabled: true
  use_motifs: true
  inject_from_memory: false
  fallback_only: false
introspect: false
use_memory: false
use_structural_attention: true
structural_attention_weight: 0.2
lazy_memory: false
memory_similarity_threshold: 0.80
memory_diagnostics: true
ignore_memory_shape_constraint: true
sparse_mode: false
fallback_on_abstraction_fail: false
regime_thresholds:
  entropy_low: 0.1
  zone_alignment_cutoff: 0.3
  symmetry_cutoff: 0.5
